mac_arm64: clean
	GOOS=darwin GOARCH=arm64 go build

mac_amd64: clean
	GOOS=darwin GOARCH=amd64 go build

win_amd64: clean
	GOOS=windows GOARCH=amd64 go build

linux_amd64: clean
	GOOS=linux GOARCH=amd64 go build

clean:
	rm -f tablesort
